<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
	<link rel="stylesheet" type="text/css" href="www/public/css/main.css">
	<script type="text/javascript" src="www/public/js/main.js" async></script>
</head>
<body>

<p>BowerGulpKoaSeed</p>

</body>
</html>
